To : debian-devel@lists.debian.org
Subject : Re: Call for testers: DPut version 1.0.0
From : Jonathan Carter <jcc@debian.org>
Date : Mon, 7 Aug 2017 17:28:34 -0400
Message-id : 3e865651-afa0-3300-029a-d5ad0f75dd12@debian.org
In-reply-to : <[ðŸ”Ž]Â 85lgmwnrkm.fsf@benfinney.id.au>
References : <[ðŸ”Ž]Â 85lgmwnrkm.fsf@benfinney.id.au>


Hi Ben
On 06/08/2017 20:34, Ben Finney wrote:
> Please try your strange uploads, and anything else you use â€˜dput(1)â€™ and
> â€˜dcut(1)â€™ for, with varying configurations. If there are any regressions
> I want you to report them in the Debian BTS, so they can be investigated
> before a wider release.
> 
> If anyone has unusual use cases that are feasible for automation, I am
> also interested in setting up an automated feature test suite. Please
> contact me at <dput@packages.debian.org>.
> 
> Thanks in advance for your help to improve DPut!
I get the following:
"""
Traceback (most recent call last):
  File "/usr/bin/dput", line 11, in <module>
    load_entry_point('dput==1.0.0', 'console_scripts', 'execute-dput')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/dput/dput/dput.py", line 28, in <module>
    from . import crypto
  File "/usr/share/dput/dput/crypto.py", line 14, in <module>
    import gpg
  File "/usr/lib/python3/dist-packages/gpg/__init__.py", line 101, in
<module>
    from . import core
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 36, in <module>
    from . import constants
  File "/usr/lib/python3/dist-packages/gpg/constants/__init__.py", line
28, in <module>
    from . import data, keylist, sig, tofu # The subdirs.
ImportError: cannot import name 'tofu'
"""
I looked for tofu but there only seems to be a python-tofu package and
not a python3-tofu package, something I'm missing?
-Jonathan