To : Scott Kitterman <debian@kitterman.com>, debian-devel@lists.debian.org
Subject : Re: Questionable mass bug filling
From : Thomas Goirand <zigo@debian.org>
Date : Sat, 21 Apr 2018 21:37:35 +0200
Message-id : 809c9b0e-0b09-bcb0-6497-4954cfd49156@debian.org
In-reply-to : <[ðŸ”Ž]Â 0321B29F-9692-4E69-968A-E72744A294C3@kitterman.com>
References : <[ðŸ”Ž]Â bddc1b12-891c-b6ed-31e2-08eaa69d7a23@debian.org> <[ðŸ”Ž]Â 0321B29F-9692-4E69-968A-E72744A294C3@kitterman.com>


On 04/21/2018 05:36 PM, Scott Kitterman wrote:
> 
> 
> On April 21, 2018 3:05:54 PM UTC, Thomas Goirand <zigo@debian.org> wrote:
>> Hi Helmut,
> ...
>> Also, some of the bugs are questionable at least. While yes, the python
>> modules can't be imported, it doesn't seem it's been done in the
>> context
>> of actually using the Python module. For example, importing a sphinx
>> plugin python module without having sphinx being installed is kind of a
>> useless test. In reality, you wouldn't do that, you'd just invoke
>> sphinx.
> ...
> 
> I see your point about the practical implications of this kind of bug, but I think the bug is valid.  It's a missing depends since the plugin needs sphinx to work.
> 
> Scott K
Right. I've spent a few hours to fix it on all of my packages anyways.
The only thing I regret at this point, is filling the bug twice instead
of only once (ie: only once for both py2 and py3 is enough). It was hard
to read in the BTS, and it's now kind of a mess, even though all bugs
are closed, I believe.
Cheers,
Thomas Goirand (zigo)