To : Debian Bug Tracking System <submit@bugs.debian.org>
Subject : Bug#910960: ITP: python-outcome -- capture the outcome of Python function calls
From : Robie Basak <robie@justgohome.co.uk>
Date : Sat, 13 Oct 2018 20:51:21 +0100
Message-id : 20181013195121.GA27405@mal.justgohome.co.uk
Reply-to : Robie Basak <robie@justgohome.co.uk>, 910960@bugs.debian.org


Package: wnpp
Severity: wishlist
Owner: Robie Basak <robie@justgohome.co.uk>
* Package name    : python-outcome
  Version         : 1.0.0-1
  Upstream Author : Nathaniel J. Smith <njs@pobox.com>
* URL             : https://github.com/python-trio/outcome
* License         : Apache-2.0 or Expat
  Programming Lang: Python
  Description     : capture the outcome of Python function calls
 Outcome provides a function `capture' for capturing the outcome of a Python
 function call, so that it can be passed around - even if the function raises
 an exception. It also provides the async equivalent function `acapture'.
This is a dependency of trio, ITP bug #900296
I intend to join the DPMT and then maintain it there, but as I'm not a
member right now, I will take things a step at a time and get it into
unstable first.
signature.asc